FROM node:18-alpine

WORKDIR /app/

COPY ./src/client /app/src/client
COPY package.json yarn.lock vite.config.ts uno.config.ts tsconfig.*.json /app/

RUN yarn install
RUN set -ex && ls

RUN yarn build-only
