# Generated by Django 4.2.2 on 2023-06-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="add_amount",
            new_name="AddAmount",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="bic",
            new_name="BIC",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="bank_name",
            new_name="BankName",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="birth_date",
            new_name="BirthDate",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="cbc",
            new_name="CBC",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="category",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="child_fio",
            new_name="ChildFio",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="class_num",
            new_name="ClassNum",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="contract",
            new_name="Contract",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="corresp_acc",
            new_name="CorrespAcc",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="counter_id",
            new_name="CounterId",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="counter_val",
            new_name="CounterVal",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="doc_idx",
            new_name="DocIdx",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="drawer_status",
            new_name="DrawerStatus",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="exec_id",
            new_name="ExecId",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="first_name",
            new_name="FirstName",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="flat",
            new_name="Flat",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="inst_num",
            new_name="InstNum",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="kpp",
            new_name="KPP",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="last_name",
            new_name="LastName",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="middle_name",
            new_name="MiddleName",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="name",
            new_name="Name",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="payee_inn",
            new_name="PayeeINN",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="payer_address",
            new_name="PayerAddress",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="payer_inn",
            new_name="PayerINN",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="payer_id_num",
            new_name="PayerIdNum",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="payer_id_type",
            new_name="PayerIdType",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="paym_period",
            new_name="PaymPeriod",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="paym_term",
            new_name="PaymTerm",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="pens_acc",
            new_name="PensAcc",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="pers_acc",
            new_name="PersAcc",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="personal_acc",
            new_name="PersonalAcc",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="personal_account",
            new_name="PersonalAccount",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="phone",
            new_name="Phone",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="purpose",
            new_name="Purpose",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="quitt_date",
            new_name="QuittDate",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="quitt_id",
            new_name="QuittId",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="reg_type",
            new_name="RegType",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="rule_id",
            new_name="RuleId",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="service_name",
            new_name="ServiceName",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="spec_fio",
            new_name="SpecFio",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="sum",
            new_name="Sum",
        ),
        migrations.RenameField(
            model_name="paymentreceipt",
            old_name="uin",
            new_name="UIN",
        ),
        migrations.RemoveField(
            model_name="paymentreceipt",
            name="tech_code",
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="TechCode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Мобильная связь, стационарный телефон"),
                    ("02", "Коммунальные услуги, ЖКХ"),
                    ("03", "ГИБДД, налоги, пошлины, бюджетные платежи"),
                    ("04", "Охранные услуги"),
                    ("05", "Услуги, оказываемые УФМС"),
                    ("06", "ПФР"),
                    ("07", "Погашение кредитов"),
                    ("08", "Образовательные учреждения"),
                    ("09", "Интернет и ТВ"),
                    ("10", "Электронные деньги"),
                    ("11", "Отдых и путешествия"),
                    ("12", "Инвестиции и страхование"),
                    ("13", "Спорт и здоровье"),
                    ("14", "Благотворительные и общественные организации"),
                    ("15", "Прочие услуги"),
                ],
                help_text="Может использоваться принимающей организацией для вызова соответствующей обрабатывающей ИТ-системы.",
                max_length=2,
                null=True,
                verbose_name="Технический код, рекомендуемый для заполнения поставщиком услуг.",
            ),
        ),
    ]
