# Generated by Django 4.2.2 on 2023-06-27 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_paymentreceipt_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория платежа",
                "verbose_name_plural": "Категории платежей",
            },
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.paymentcategory",
                verbose_name="Категория",
            ),
        ),
    ]
